package com.nwdaf.Analytics.Model;

public enum NwdafEvent {

    LOAD_LEVEL_INFORMATION,
    NETWORK_PERFORMANCE,
    NF_LOAD,
    QOS_SUSTAINABILITY,
    SERVICE_EXPERIENCE,
    UE_MOBILITY,
    UE_COMM,
    USER_DATA_CONGESTION,
    ABNORMAL_BEHAVIOUR;
}
