package com.nwdaf.Analytics.Model.CustomData;

public enum AmfEventType {

    LOCATION_REPORT,
    PRESENCE_IN_AOI_REPORT,
    TIMEZONE_REPORT,
    ACCESS_TYPE_REPORT,
    REGISTRATION_STATE_REPORT,
    CONNECTIVITY_STATE_REPORT,
    REACHABILITY_REPORT,
    COMMUNICATION_FAILURE_REPORT,
    UES_IN_AREA_REPORT,
    SUBSCRIPTION_ID_CHANGE,
    SUBSCRIPTION_ID_ADDITION,
    LOSS_OF_CONNECTIVITY;
}
