package com.nwdaf.Analytics.Model.CustomData.AbnormalBehaviour;

public enum ExceptionId {

    UNEXPECTED_UE_LOCATION,
    UNEXPECTED_LONG_LIVE_FLOW,
    UNEXPECTED_LARGE_RATE_FLOW,
    UNEXPECTED_WAKEUP,
    SUSPICION_OF_DDOS_ATTACK,
    WRONG_DESTINATION_ADDRESS,
    TOO_FREQUENT_SERVICE_ACCESS,
    ABNORMAL_TRAFFIC_VOLUME,
    UNEXPECTED_RADIO_LINK_FAILURES,
    PING_PONG_ACROSS_CELLS;
}
